### ISSUE TITLE
[FEATURE] Package name

### ISSUE THREAD

**Issue by ghiggi** [ghiggi/ximage#1]
Hey there @a358003542 ! We would like to further develop and publish this software on pypi but your package ximage (https://pypi.org/project/ximage/) already uses the desired name. We saw that your project is archived ... would you be willing to pass it to us?

We are interested in developing a well-maintained software around xarray for n-dimensional array image processing ;)

**Comment by a358003542** [comment]
It has been deleted. @ghiggi
